# Generated by Django 5.2.6 on 2025-09-04 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('math_facts', 'Math Facts Practice'), ('anagram_hunt', 'Anagram Hunt')], max_length=32)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('score', models.IntegerField()),
                ('finished_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-finished_at'],
            },
        ),
    ]
